# Generated by Django 3.2.3 on 2021-05-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_dart_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('one_dart_avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('total_games', models.IntegerField()),
                ('highest_finish', models.IntegerField()),
                ('doubles_hit', models.IntegerField()),
                ('hit_180', models.IntegerField()),
                ('hit_160_179', models.IntegerField()),
                ('hit_140_159', models.IntegerField()),
                ('hit_120_139', models.IntegerField()),
                ('hit_100_119', models.IntegerField()),
                ('hit_80_99', models.IntegerField()),
                ('hit_60_79', models.IntegerField()),
                ('hit_0_59', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.users')),
            ],
        ),
    ]
