services:
  api:
    container_name: dev_api
    ports: 
      - 8000:8000
    depends_on:
      - db
    command: bash -c "pip install -r requirements.txt && python api/manage.py makemigrations && python api/manage.py migrate && python api/manage.py runserver 0.0.0.0:8000"
  db:
    container_name: dev_db
    volumes:
      - "dev_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=dartshub
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
volumes:
  dev_db:
