
version: '3'
services:
  redis:
    image: redis:alpine
    ports: 
       - "6379:6379"
  api:
    image: python:latest
    working_dir: /code
    links:
      - redis
    volumes:
      - type: bind
        source: ./server
        target: /code
  db:
    image: postgres
    environment: 
      - POSTGRES_DB=dartshub
      - POSTGRES_PASSWORD=pass
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:

