# Generated by Django 3.2.3 on 2021-05-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_stats_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
