# Generated by Django 3.2.3 on 2021-05-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_dart_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('one_dart_avg', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('highest_finish', models.IntegerField(default=0)),
                ('doubles_hit', models.IntegerField(default=0)),
                ('hit_180', models.IntegerField(default=0)),
                ('hit_160_179', models.IntegerField(default=0)),
                ('hit_140_159', models.IntegerField(default=0)),
                ('hit_120_139', models.IntegerField(default=0)),
                ('hit_100_119', models.IntegerField(default=0)),
                ('hit_80_99', models.IntegerField(default=0)),
                ('hit_60_79', models.IntegerField(default=0)),
                ('hit_0_59', models.IntegerField(default=0)),
            ],
        ),
    ]
